/**
 * Loads the shared deployment artifacts.
 *
 * `shared/marco-artifacts/` is generated by `scripts/localnet.sh` and is the
 * only place addresses are allowed to come from. Hand-copying a program id is
 * how `preipovaults/app` ended up pointing at Anchor's placeholder
 * `Fg6PaFpo…`, which fails as a wallet error rather than as anything that
 * names the real cause.
 */

import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { PublicKey } from '@solana/web3.js';
import type { Idl } from '@coral-xyz/anchor';

const HERE = dirname(fileURLToPath(import.meta.url));
const DEFAULT_ROOT = join(HERE, '..', '..', '..', '..', 'shared', 'marco-artifacts');

export interface MarcoAddresses {
  readonly cluster: string;
  readonly rpcUrl: string;
  readonly programs: { readonly marcoSpot: string; readonly marcoVault: string };
  readonly usdc: { readonly mint: string; readonly decimals: number };
  readonly wallets: {
    readonly admin: string;
    readonly operator: string;
    readonly treasury: string;
    readonly broker: string;
    readonly demoTrader: string;
  };
  readonly tokenAccounts: {
    readonly brokerUsdc: string;
    readonly treasuryUsdc: string;
    readonly demoTraderUsdc: string;
  };
}

export interface MarcoArtifacts {
  readonly addresses: MarcoAddresses;
  readonly spotIdl: Idl;
  readonly vaultIdl: Idl;
  readonly spotProgramId: PublicKey;
  readonly vaultProgramId: PublicKey;
  readonly usdcMint: PublicKey;
  readonly admin: PublicKey;
  readonly treasury: PublicKey;
}

function readJson<T>(path: string, what: string): T {
  if (!existsSync(path)) {
    throw new Error(`${what} not found at ${path} — run 'sh scripts/localnet.sh' first`);
  }
  return JSON.parse(readFileSync(path, 'utf8')) as T;
}

export function loadArtifacts(root: string = DEFAULT_ROOT): MarcoArtifacts {
  const addresses = readJson<MarcoAddresses>(join(root, 'addresses.json'), 'addresses.json');
  const spotIdl = readJson<Idl>(join(root, 'idl', 'marco_spot.json'), 'marco_spot IDL');
  const vaultIdl = readJson<Idl>(join(root, 'idl', 'marco_vault.json'), 'marco_vault IDL');

  // The IDL carries the program id it was built for. If that disagrees with
  // addresses.json, one of them is stale and every PDA derived from either
  // would be silently wrong, so refuse rather than guess.
  for (const [name, idl, expected] of [
    ['marco_spot', spotIdl, addresses.programs.marcoSpot],
    ['marco_vault', vaultIdl, addresses.programs.marcoVault],
  ] as const) {
    const declared = (idl as { address?: string }).address;
    if (declared && declared !== expected) {
      throw new Error(
        `${name} IDL declares program id ${declared} but addresses.json says ${expected}. ` +
          `Re-run 'anchor build' and 'sh scripts/localnet.sh'.`,
      );
    }
  }

  return {
    addresses,
    spotIdl,
    vaultIdl,
    spotProgramId: new PublicKey(addresses.programs.marcoSpot),
    vaultProgramId: new PublicKey(addresses.programs.marcoVault),
    usdcMint: new PublicKey(addresses.usdc.mint),
    admin: new PublicKey(addresses.wallets.admin),
    treasury: new PublicKey(addresses.wallets.treasury),
  };
}
